version: "3.3"
services:
  jmeter:
    container_name: "jmeter"
#   build: ./docker
    image: registry.tochka-tech.com/oci_qa-core/jmeter:latest
    environment:
    - _ALLURE_REPORT_PATH=${_ALLURE_REPORT_PATH}
    - _ALLURE_CONFIG_PATH=${_ALLURE_CONFIG_PATH}
    - JMETER_PATH=${JMETER_PATH}
#ouath credentials
    - _oauth_login=${_oauth_login}
    - _oauth_password=${_oauth_password}
#Данные от CASPER_DB_STAGE
    - STEPLER_DB_URL_Stage=${STEPLER_DB_URL_Stage}
    - STEPLER_DB_USERNAME_Stage=${STEPLER_DB_USERNAME_Stage}
    - STEPLER_DB_PASSWORD_Stage=${STEPLER_DB_PASSWORD_Stage} 
#Данные от CASPER_DB_PRE
    - STEPLER_DB_URL_Pre=${STEPLER_DB_URL_Pre}
    - STEPLER_DB_USERNAME_Pre=${STEPLER_DB_USERNAME_Pre}
    - STEPLER_DB_PASSWORD_Pre=${STEPLER_DB_PASSWORD_Pre} 
#Бейсик вторизация в апибанке степлера
    - APIBANKA_BASIC_STEPLER_Stage=${APIBANKA_BASIC_STEPLER_Stage}
    - APIBANKA_BASIC_STEPLER_Pre=${APIBANKA_BASIC_STEPLER_Pre}
#Данные от CBS_DB_STAGE
    - CBS_DB_URL_Stage=${CBS_DB_URL_Stage}
    - CBS_DB_USERNAME_Stage=${CBS_DB_USERNAME_Stage}
    - CBS_DB_PASSWORD_Stage=${CBS_DB_PASSWORD_Stage}
#Данные от CBS_DB_PRE
    - CBS_DB_URL_Pre=${CBS_DB_URL_Pre}
    - CBS_DB_USERNAME_Pre=${CBS_DB_USERNAME_Pre}
    - CBS_DB_PASSWORD_Pre=${CBS_DB_PASSWORD_Pre}
#Приколоченные консул слои
    - CONSUL_LAYER_Stage=test
    - CONSUL_LAYER_Pre=pre
#Бейсик вторизация в админке степлера
    - STEPLER_BASIC_ADMIN=${STEPLER_BASIC_ADMIN}
    volumes:
      - ./:${JMETER_PATH}
    command: jmeter -n -t ${JMETER_PATH}/test-plan/${FILE_NAME}.jmx -Jlayer=${LAYER} -Jusers=${USERS_NUMBER} -l /result/allure-results/result.jtl -j /result/jmeter.log -e -o /result/report/ 
