version: "3.3"
services:
  jmeter:
    container_name: "jmeter"
#   build: ./docker
    image: registry.tochka-tech.com/oci_qa-core/jmeter:latest
    environment:
    - _ALLURE_REPORT_PATH=${_ALLURE_REPORT_PATH}
    - _ALLURE_CONFIG_PATH=${_ALLURE_CONFIG_PATH}
    - JMETER_PATH=${JMETER_PATH}
#ouath credentials
    - _oauth_login=${_oauth_login}
    - _oauth_password=${_oauth_password} 
#Данные от AUSN_DB_STAGE
    - AUSN_DB_URL_Stage=${AUSN_DB_URL_Stage}
    - AUSN_DB_USERNAME_Stage=${AUSN_DB_USERNAME_Stage}
    - AUSN_DB_PASSWORD_Stage=${AUSN_DB_PASSWORD_Stage} 
#Данные от AUSN_DB_PRE
    - AUSN_DB_URL_Pre=${AUSN_DB_URL_Pre}
    - AUSN_DB_USERNAME_Pre=${AUSN_DB_USERNAME_Pre}
    - AUSN_DB_PASSWORD_Pre=${AUSN_DB_PASSWORD_Pre} 
#Данные от STEPLER_DB_STAGE
    - STEPLER_DB_URL_Stage=${STEPLER_DB_URL_Stage}
    - STEPLER_DB_USERNAME_Stage=${STEPLER_DB_USERNAME_Stage}
    - STEPLER_DB_PASSWORD_Stage=${STEPLER_DB_PASSWORD_Stage}
#Данные от STEPLER_DB_PRE
    - STEPLER_DB_URL_Pre=${STEPLER_DB_URL_Pre}
    - STEPLER_DB_USERNAME_Pre=${STEPLER_DB_USERNAME_Pre}
    - STEPLER_DB_PASSWORD_Pre=${STEPLER_DB_PASSWORD_Pre}
#Данные от SKREPKA_DB_STAGE
    - SKREPKA_DB_URL_Stage=${SKREPKA_DB_URL_Stage}
    - SKREPKA_DB_USERNAME_Stage=${SKREPKA_DB_USERNAME_Stage}
    - SKREPKA_DB_PASSWORD_Stage=${SKREPKA_DB_PASSWORD_Stage}
#Данные от SKREPKA_DB_PRE
    - SKREPKA_DB_URL_Pre=${SKREPKA_DB_URL_Pre}
    - SKREPKA_DB_USERNAME_Pre=${SKREPKA_DB_USERNAME_Pre}
    - SKREPKA_DB_PASSWORD_Pre=${SKREPKA_DB_PASSWORD_Pre}
#Данные от RS_DB_STAGE
    - RS_DB_URL_Stage=${RS_DB_URL_Stage}
    - RS_DB_USERNAME_Stage=${RS_DB_USERNAME_Stage}
    - RS_DB_PASSWORD_Stage=${RS_DB_PASSWORD_Stage}
#Данные от RS_DB_PRE
    - RS_DB_URL_Pre=${RS_DB_URL_Pre}
    - RS_DB_USERNAME_Pre=${RS_DB_USERNAME_Pre}
    - RS_DB_PASSWORD_Pre=${RS_DB_PASSWORD_Pre}
#Бейсик вторизация в апибанке степлера
    - APIBANKA_BASIC_STEPLER_Stage=${APIBANKA_BASIC_STEPLER_Stage}
    - APIBANKA_BASIC_STEPLER_Pre=${APIBANKA_BASIC_STEPLER_Pre}
#Данные от CBS_DB_STAGE
    - CBS_DB_URL_Stage=${CBS_DB_URL_Stage}
    - CBS_DB_USERNAME_Stage=${CBS_DB_USERNAME_Stage}
    - CBS_DB_PASSWORD_Stage=${CBS_DB_PASSWORD_Stage}
#Данные от CBS_DB_PRE
    - CBS_DB_URL_Pre=${CBS_DB_URL_Pre}
    - CBS_DB_USERNAME_Pre=${CBS_DB_USERNAME_Pre}
    - CBS_DB_PASSWORD_Pre=${CBS_DB_PASSWORD_Pre}
#Приколоченные консул слои
    - CONSUL_LAYER_Stage=test
    - CONSUL_LAYER_Pre=pre
    - REGISTER_LAYER_Stage=stage
    - REGISTER_LAYER_Pre=pre
#Бейсик  авторизация степлера
    - STEPLER_BASIC_ADMIN=${STEPLER_BASIC_ADMIN}
    - STEPLER_BASIC_YOOKASSA=${STEPLER_BASIC_YOOKASSA}
#Бейсик авторизации от кролика скрепки
    - SKREKPA_BASIC_MQ=${SKREKPA_BASIC_MQ}
#Данные от TRANSPORTIR state
    - TRANSPORTIR_DB_URL_Stage=${TRANSPORTIR_DB_URL_Stage}
    - TRANSPORTIR_DB_USERNAME_Stage=${TRANSPORTIR_DB_USERNAME_Stage}
    - TRANSPORTIR_DB_PASSWORD_Stage=${TRANSPORTIR_DB_PASSWORD_Stage}
#Данные от TRANSPORTIR pre
    - TRANSPORTIR_DB_URL_Pre=${TRANSPORTIR_DB_URL_Pre}
    - TRANSPORTIR_DB_USERNAME_Pre=${TRANSPORTIR_DB_USERNAME_Pre}
    - TRANSPORTIR_DB_PASSWORD_Pre=${TRANSPORTIR_DB_PASSWORD_Pre}
    volumes:
      - ./:${JMETER_PATH}
    command: jmeter -n -t ${JMETER_PATH}/test-plan/${FILE_NAME}.jmx -Jlayer=${LAYER} -Jusers=${USERS_NUMBER} -l /result/allure-results/result.jtl -j /result/jmeter.log -e -o /result/report/ 
